---
title: How to plot a interactive chart with Rshiny in blogdown
author: Diego Staphorst
date: '2019-11-18'
slug: how-to-plot-a-interactive-chart-with-rshiny-in-blogdown
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2019-11-18T14:33:00+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
runtime: shiny
output: html_document
---


#Introduction
In this short tech report, we show off how to include interactive charts into your post. We do this by deploying R-Shiny application online and embedding this withing the post. These app's are deployed on https://www.shinyapps.io/, and will be sent to this platform via the library: rsconnect.

For this post we made use of the [Shiny example: Diamonds Explorer](https://gist.github.com/jcheng5/3239667). The app is built from [2 seperate files](https://shiny.rstudio.com/articles/two-file.html), one file (ui.R) includes the code to define the user interface. The second file (server.R) contains the code to serve the correct data files to the interface. By seperating these dependencies, it makes it easier to handle the code.

Since this post goes beyond the scope of explaining the code in the R files, we will skip that. Underneath you are able to interact with the rShiny application.

<iframe frameborder="no"  src="https://hva-diego.shinyapps.io/shinyapps" style="overflow:hidden;position:relative;width:100%;height:800px;"> </iframe>


